-- ===========================================================================
-- SCRIPT DE CRIAÇÃO E MIGRAÇÃO DAS TABELAS DO SISTEMA AGENDA INTEGRADA
-- DESTINO: SUPABASE / POSTGRESQL
-- PROJETO: vvdbbwgcubddfvsxsehb (https://vvdbbwgcubddfvsxsehb.supabase.co)
-- ===========================================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 0. REMOÇÃO DE TABELAS ANTIGAS/INCOMPLETAS (PARA EVITAR ERRO DE COLUNAS FALTANTES)
---------------------------------------------------------------------------
DROP TABLE IF EXISTS public.planning_links CASCADE;
DROP TABLE IF EXISTS public.attachments CASCADE;
DROP TABLE IF EXISTS public.demand_updates CASCADE;
DROP TABLE IF EXISTS public.demands CASCADE;
DROP TABLE IF EXISTS public.planning_items CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;
DROP TABLE IF EXISTS public.access_profiles CASCADE;
DROP TABLE IF EXISTS public.kanban_stages CASCADE;
DROP TABLE IF EXISTS public.priority_levels CASCADE;
DROP TABLE IF EXISTS public.categories CASCADE;
DROP TABLE IF EXISTS public.schools CASCADE;

-- 1. DDL DE CRIAÇÃO DAS TABELAS
---------------------------------------------------------------------------
-- Tabela: schools
CREATE TABLE public.schools (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    director TEXT,
    address TEXT,
    phone TEXT,
    email TEXT,
    code TEXT,
    external_id TEXT,
    lat DOUBLE PRECISION,
    lon DOUBLE PRECISION,
    active INTEGER NOT NULL DEFAULT 1
);

-- Tabela: users
CREATE TABLE public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL,
    school_id BIGINT REFERENCES public.schools(id) ON DELETE SET NULL,
    active INTEGER NOT NULL DEFAULT 1
);

-- Tabela: access_profiles
CREATE TABLE public.access_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT UNIQUE NOT NULL,
    label TEXT NOT NULL,
    description TEXT,
    school_scoped INTEGER NOT NULL DEFAULT 0,
    can_edit_analysis INTEGER NOT NULL DEFAULT 1,
    can_manage_admin INTEGER NOT NULL DEFAULT 0,
    can_view_reports INTEGER NOT NULL DEFAULT 1,
    can_view_planning INTEGER NOT NULL DEFAULT 1,
    is_system INTEGER NOT NULL DEFAULT 0,
    active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);

-- Tabela: categories
CREATE TABLE public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    icon TEXT NOT NULL DEFAULT 'wrench',
    color TEXT NOT NULL DEFAULT 'blue',
    hint TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    active INTEGER NOT NULL DEFAULT 1
);

-- Tabela: priority_levels
CREATE TABLE public.priority_levels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    label TEXT NOT NULL,
    hint TEXT,
    color TEXT NOT NULL DEFAULT 'red',
    rank INTEGER NOT NULL
);

-- Tabela: kanban_stages
CREATE TABLE public.kanban_stages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stage_key TEXT UNIQUE NOT NULL,
    label TEXT NOT NULL,
    hint TEXT,
    accent TEXT NOT NULL DEFAULT 'blue',
    statuses TEXT NOT NULL,
    target_status TEXT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0
);

-- Tabela: demands
CREATE TABLE public.demands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    category TEXT NOT NULL,
    subcategory TEXT,
    location TEXT,
    impact TEXT,
    affected_people INTEGER DEFAULT 0,
    risk INTEGER DEFAULT 0,
    blocks_activity INTEGER DEFAULT 0,
    school_id BIGINT NOT NULL REFERENCES public.schools(id) ON DELETE CASCADE,
    priority TEXT NOT NULL DEFAULT 'P3',
    status TEXT NOT NULL DEFAULT 'Nova',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    due_date TEXT,
    responsible TEXT,
    sector TEXT,
    cost_estimate DOUBLE PRECISION DEFAULT 0,
    action_defined TEXT,
    technical_opinion TEXT,
    dependencies TEXT,
    needs_visit INTEGER DEFAULT 0,
    needs_budget INTEGER DEFAULT 0,
    needs_material INTEGER DEFAULT 0,
    needs_contract INTEGER DEFAULT 0,
    future_year INTEGER,
    planning_kind TEXT,
    planned_quantity DOUBLE PRECISION DEFAULT 0,
    planned_unit TEXT,
    created_by BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    prov_description TEXT,
    prov_action_type TEXT,
    prov_responsible TEXT,
    prov_due_date TEXT,
    prov_priority TEXT,
    prov_note TEXT,
    prov_notify_school INTEGER NOT NULL DEFAULT 0
);

-- Tabela: demand_updates
CREATE TABLE public.demand_updates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    demand_id BIGINT NOT NULL REFERENCES public.demands(id) ON DELETE CASCADE,
    kind TEXT NOT NULL,
    message TEXT NOT NULL,
    author TEXT NOT NULL,
    visibility TEXT NOT NULL DEFAULT 'public',
    created_at TEXT NOT NULL
);

-- Tabela: attachments
CREATE TABLE public.attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    demand_id BIGINT NOT NULL REFERENCES public.demands(id) ON DELETE CASCADE,
    category TEXT,
    filename TEXT NOT NULL,
    stored_name TEXT NOT NULL,
    mime TEXT,
    size BIGINT DEFAULT 0,
    created_at TEXT NOT NULL
);

-- Tabela: planning_items
CREATE TABLE public.planning_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE,
    year INTEGER NOT NULL,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    kind TEXT NOT NULL,
    status TEXT NOT NULL,
    estimated_cost DOUBLE PRECISION DEFAULT 0,
    quantity DOUBLE PRECISION DEFAULT 0,
    unit TEXT,
    justification TEXT,
    schools_count INTEGER DEFAULT 1,
    process_number TEXT,
    procurement_number TEXT,
    contract_number TEXT,
    supplier TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

-- Tabela: planning_links
CREATE TABLE public.planning_links (
    planning_id BIGINT NOT NULL REFERENCES public.planning_items(id) ON DELETE CASCADE,
    demand_id BIGINT NOT NULL REFERENCES public.demands(id) ON DELETE CASCADE,
    PRIMARY KEY (planning_id, demand_id)
);

-- 2. POLÍTICAS DE SEGURANÇA (ROW LEVEL SECURITY - RLS)
---------------------------------------------------------------------------
ALTER TABLE public.schools ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir acesso completo em schools" ON public.schools;
CREATE POLICY "Permitir acesso completo em schools" ON public.schools FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir acesso completo em users" ON public.users;
CREATE POLICY "Permitir acesso completo em users" ON public.users FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.access_profiles ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir acesso completo em access_profiles" ON public.access_profiles;
CREATE POLICY "Permitir acesso completo em access_profiles" ON public.access_profiles FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir acesso completo em categories" ON public.categories;
CREATE POLICY "Permitir acesso completo em categories" ON public.categories FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.priority_levels ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir acesso completo em priority_levels" ON public.priority_levels;
CREATE POLICY "Permitir acesso completo em priority_levels" ON public.priority_levels FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.kanban_stages ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir acesso completo em kanban_stages" ON public.kanban_stages;
CREATE POLICY "Permitir acesso completo em kanban_stages" ON public.kanban_stages FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.demands ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir acesso completo em demands" ON public.demands;
CREATE POLICY "Permitir acesso completo em demands" ON public.demands FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.demand_updates ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir acesso completo em demand_updates" ON public.demand_updates;
CREATE POLICY "Permitir acesso completo em demand_updates" ON public.demand_updates FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.attachments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir acesso completo em attachments" ON public.attachments;
CREATE POLICY "Permitir acesso completo em attachments" ON public.attachments FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.planning_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir acesso completo em planning_items" ON public.planning_items;
CREATE POLICY "Permitir acesso completo em planning_items" ON public.planning_items FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.planning_links ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Permitir acesso completo em planning_links" ON public.planning_links;
CREATE POLICY "Permitir acesso completo em planning_links" ON public.planning_links FOR ALL USING (true) WITH CHECK (true);

-- 3. ÍNDICES DE DESEMPENHO
---------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_demands_school_id ON public.demands(school_id);
CREATE INDEX IF NOT EXISTS idx_demands_status ON public.demands(status);
CREATE INDEX IF NOT EXISTS idx_demands_priority ON public.demands(priority);
CREATE INDEX IF NOT EXISTS idx_demand_updates_demand_id ON public.demand_updates(demand_id);
CREATE INDEX IF NOT EXISTS idx_attachments_demand_id ON public.attachments(demand_id);
CREATE INDEX IF NOT EXISTS idx_users_email ON public.users(email);

-- 4. POPULAÇÃO DOS DADOS EXISTENTES (DML)
---------------------------------------------------------------------------
-- Inserindo 65 registro(s) em schools
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (1, 'E.M. Prefeito Otoni Rocha', 'TANIA MARIA DA SILVA MEDEIROS', 'RuaTravessa Pedro Augusto, s/n - Centro - Itaguaí/RJ - CEP: 23821-210', '21 98414-8338', 'em.prefotonirocha@edu.itaguai.rj.gov.br', NULL, '1cefd2ff-55ea-449d-a94e-6b7dcea4453a', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (2, 'Colégio M. Senador Teotônio Vilella', 'Cássia Regina R. da Silva', 'Rua Ivete Lino Ribeiro, nº 22 - Centro - Itaguaí/RJ - CEP: 23810-540', '(21) 97026-4258', 'cm.senadorteotoniovilella@edu.itaguai.rj.gov.br', NULL, 'afaf97d9-fa67-4b61-b580-5d88911f1ca0', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (3, 'E.M. João Vicente Soares', 'LUCIANA KARLA DE OLIVEIRA CICARINO', 'Av. Machado de Assis c/ a Rua Cesar Lattes, s/n - Vila Ibirapitanga - Itaguaí/RJ - CEP: 23811-140', '21 96424-5859', 'em.joaovicentesoares@edu.itaguai.rj.gov.br', NULL, '6d2574af-9599-4027-acaf-fb088dca7d20', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (4, 'E.M. Oscar José de Souza', 'ERIKA FRANCISCA FERREIRA SILVA DE MATOS', 'Rua Lucia Tieme Hara, s/n - Santana - Itaguaí/RJ - CEP: 23810-170', '21 97133-0378', 'em.oscarjosedesouza@edu.itaguai.rj.gov.br', NULL, '6a4f5b1b-0745-4a5d-a5e3-47227c91beb2', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (5, 'E. M. VER. PROFESSOR ARTHUR BRITO DE CASTRO', 'MARIA JOSE DE ANDRADE MARIANO', 'Itaguaí/RJ', '21 96931-0516', 'em.verprofessorarthurbritodecastro@edu.itaguai.rj.gov.br', NULL, 'aff3d54e-e671-4f6f-9248-a4197f49dd3a', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (6, 'C.M. Profª Teresinha de Jesus Campos de Farias', 'Lucia Sayuri Yokoyama Sagava', 'R. Antônio M Pereira, nº 149 - Itaguaí/RJ', '21 985232368', 'cm.teresinhadejesuscamposdefarias@edu.itaguai.rj.gov.br', NULL, '55c3c54c-82d3-437c-acd0-98b5cc97781a', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (7, 'C.M. Aparecida Azêdo', 'Luciana Lisboa', 'Estrada do Teixeira, nº 2 - Vista Alegre - Itaguaí/RJ - CEP: 23820-275', '(21) 99323-3809', 'cm.aparecidaazedo@edu.itaguai.rj.gov.br', '33228019', 'fbe4db60-c40d-43c7-9fdb-3e1f2e740658', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (8, 'C.M. Danielle Batista da Silva', 'NINAH DE FREITAS RIBEIRO', 'Rua A, s/n (Qd 06, Lt 26) - Vila Ibirapitanga - Itaguaí/RJ - CEP: 23811-703', '(21) 96487-8016', 'cm.daniellebatistadasilva@edu.itaguai.rj.gov.br', NULL, '651e49dc-f172-4428-a44f-272a4d2b156e', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (9, 'C.M. Edson Cruz Amado', 'Bianca Gonçalves da Silva', 'Rua Argentina, s/n (esquina com a Rua Bolívia, Qd. 16) - Jardim América - Itaguaí/RJ - CEP: 23810-130', '(21) 96930-7327', 'cm.edsoncruzamado@edu.itaguai.rj.gov.br', '33439290', '18eb69f3-7226-4c1d-b875-94a5a03a91f1', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (10, 'C.M. Euclydes José Borges', 'Denise Spoliante Salutti', 'Rua Salim Francisco do Nascimento, nº (Antiga Rua 41) - Engenho - Itaguaí/RJ - CEP: 23820-100', '(21) 96468-9552', 'cm.euclydesjoseborges@edu.itaguai.rj.gov.br', NULL, '0180b6c6-c49b-43fc-b70d-f4807151b32c', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (11, 'C.M. Florentino Elias', 'MARIA ROZINETE MOREIRA DE OLIVEIRA', 'Rua das Tulipas, s/n - Parque Primavera - Itaguaí/RJ - CEP: 23830-400', '(21) 97572-8405', 'cm.florentinoelias@edu.itaguai.rj.gov.br', NULL, 'a28076db-4a53-459d-8ef8-978dc7acc7dd', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (12, 'C.M. Francisco Xavier de Moura Brito (Chico Pitanga)', 'Veronice Felix (21) 986805418', 'Rua Manoel Soares da Costa, s/n - Engenho - Itaguaí/RJ - CEP: 23821-740', '(21) 98680-5418', 'cm.franciscoxavierdemourabrito@edu.itaguai.rj.gov.br', NULL, 'cf3282c0-cd0e-41fc-a040-a93ec0cfeb59', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (13, 'C.M. Maria Eduviges do Rosario Silva', 'ADRIANA CHAVES PIRES', 'Rua Madalena Tortorrele, nº 20 (Qd. 62) - Brisamar - Itaguaí/RJ - CEP: 23825-590', '(21) 98374-7329', 'cm.mariaeduvigesdorosariosilva@edu.itaguai.rj.gov.br', NULL, '9ace17a3-764d-47d7-a9ab-2275d5434daf', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (14, 'C.M. Maria Rosa Gomes do Nascimento', 'JANILZA MARIA BISPO', 'Rua Genecildo Aguiar Vieira Teixeira, s/n - Teixeira - Itaguaí/RJ', '21 97206-8628', 'cm.mariarosagomesdonascimento@edu.itaguai.rj.gov.br', NULL, '4882aaf0-cd12-429f-8727-694a1d1d281e', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (15, 'C.M. Prof.ª Eliane Lopes Barbosa (Vila Geni)', 'INGRID CARVALHO COSTA', 'Rua Odilon Penolon Fialho, s/n - Vila Geny - Itaguaí/RJ - CEP: 23825-160', '(21) 97177-4700', 'cm.elianelopesbarbosa@edu.itaguai.rj.gov.br', NULL, 'b8fe1f4d-9fa8-464a-b403-443b54ffd127', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (16, 'C.M. Prof.ª M.ª Cristina Padela Cabral da Silva', 'RENATA MENDES VALVERDE DE OLIVEIRA GONCALVES', 'Rua Pref. José de Moraes Dias, s/n (Lote 18) - Parque Paraíso - Itaguaí/RJ - CEP: 23810-211', '(21) 96437-7241', 'cm.mariacristinapadelacabraldasilva@edu.itaguai.rj.gov.br', NULL, '03d5a82b-ef2f-4614-a020-5259bfafa502', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (17, 'C.M. Prof.ª Maria de Lurdes S. Garcia', 'ELISABETE ALVES DE OLIVEIRA RAMOS', 'Rua Machado de Assis, s/n - Vila Ibirapitanga - Itaguaí/RJ - CEP: 23811-820', '21 97145-3594', 'cm.mariadelurdessgarcia@edu.itaguai.rj.gov.br', NULL, 'eebe50f4-2abc-4437-9e51-68283ef3da5d', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (18, 'C.M. Prof.ª Tania Mara Mota de Menezes', 'ERICA CRISTINA OLIVEIRA DA SILVA', 'Rua Antônio Batista Ramos, s/n (Lt 39, Qd 18) - Brisamar - Itaguaí/RJ - CEP: 23826-155', '21 96855-3018', 'cm.taniamaramottademenezes@edu.itaguai.rj.gov.br', NULL, 'a6c18879-5445-4156-9778-aa05a039fdcc', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (19, 'C.M. Prof.º Goethe Coutinho Madruga', 'ANDREZA AZEVEDO DOS SANTOS', 'Rua dos Coqueiros, s/n (Qd. 39) - Jardim Mar - Itaguaí/RJ - CEP: 23823-120', '(21) 97990-5973', 'cm.jardimmar@edu.itaguai.rj.gov.br', NULL, 'e9680a99-5867-4252-a9b1-0117f5b98ceb', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (20, 'C.M. Prof.º Joaquim Inouê', 'ROSANGELA NASCIMENTO DA SILVA', 'Rua Dezoito, s/n (Qd. 22, Gleba A) - Chaperó - Itaguaí/RJ - CEP: 23815-000', '21 99261-9889', 'cm.joaquiminoue@edu.itaguai.rj.gov.br', NULL, 'b15ce9fa-0288-405f-be14-307d0b58176c', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (21, 'C.M. Prof.º Renato Barbosa Ladislau', 'Caroline Pedrazzi de Almeida Vieira', 'Estrada do Mazomba, s/n - Leandro - Itaguaí/RJ - CEP: 23830-000', '(21) 99422-5843', 'cm.renatobarbosaladislau@edu.itaguai.rj.gov.br', NULL, '608c43e0-f2ba-444d-953f-6748c14cf64c', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (23, 'C.M. Rita Ferreira Feijó', 'CAROLINA MONTEIRO DO NASCIMENTO PEDRO', 'Av. Guilherme Serrano, s/n (Lotes 8, Quadra C) - Vila Geny - Itaguaí/RJ - CEP: 23825-480', '21 99326-2233', 'cm.ritaferreirafeijo@edu.itaguai.rj.gov.br/', NULL, '558c9613-d276-4ebc-b9e0-95aa0d597912', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (24, 'C.M. Vereador José Antônio Carrasco', 'ANA CRISTINA BELMONTE LIMA PINHA', 'Rua Eduardo de Oliveira Júnior, s/n - Estrela do Geny - Itaguaí/RJ - CEP: 23811-480', '21 98573-6422', 'cm.estreladoceu@edu.itaguai.rj.gov.br', NULL, '2db1d115-97ba-46d7-917b-55267e801798', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (25, 'CEMAEE Centro Municipal de Atendimento Educacional Especializado', 'CRISTIANO VITOR SOUZA', 'Rua José Bonifácio, s/n - Centro - Itaguaí/RJ - CEP: 23815-650', '21 99192-4296', 'cemaee@edu.itaguai.rj.gov.br', NULL, '7d044cda-ad4d-4466-8e68-856754057278', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (26, 'CESMI-Centro Municipal de Estudos Supletivos de Itaguaí', 'LENIEDJA DA SILVA BRANDÃO BARBOSA', 'Rua João Rosa Gonzales, nº 1242 - Engenho - Itaguaí/RJ - CEP: 23820-380', '21 99370-9845', 'cesmi@edu.itaguai.rj.gov.br', NULL, '7fc75500-9132-4d61-8160-adb8ca6c6caf', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (27, 'CIEP 300 Munic. Prefeito Vicente Cicarino', 'Cleiton Magalhães Pereira dos Santos', 'Rua Professor Chico, s/n - Santana - Itaguaí/RJ - CEP: 23810-085', '(21) 96435-8547', 'ciep300@edu.itaguai.rj.gov.br', NULL, '79b7d5f7-1746-4b0d-80aa-7758ce5c1e1e', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (28, 'CIEP 496 Munic. Maestro Francisco Mignone', 'RAFAEL RIBEIRO MENEZES', 'Itaguaí/RJ - endereço cadastrado da unidade', '21 97003-0018', 'ciep496@itaguai.rj.gov.br', NULL, '58046c75-b5a5-46e5-ba7f-b38c489ba2d7', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (29, 'CIEP 497 Munic. Prof.ª Sílvia Tupinambá', 'FLAVIA MOTTA DA SILVEIRA SALGADO', 'R Manoel Soares da Costa, s/n - Engenho - Itaguaí/RJ - CEP: 23821-740', '21 97036-3871', 'ciep497@edu.itaguai.rj.gov.br', NULL, 'e06c2f23-f966-4ba9-b75d-ea799bf95ed8', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (31, 'CRECHE M. PROF. TERESINHA DE JESUS CAMPOS DE FARIAS', 'LUCIA SAYURI YOKOYAMA SAGAVA', 'Itaguaí - RJ', '21 98523-2368', NULL, NULL, 'bd5ca15e-0c9e-4428-8c02-138596b34dca', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (32, 'E. E. M. Camilo Cuquejo', 'NATALINA ALVES BATISTA', 'Estr. Jair Pereira Nascimento, s/n - Ma Geny - Itaguaí/RJ - CEP: 23830-330', '21 96476-3838', 'eem.camilocuquejo@edu.itaguai.rj.gov.br/ eemcamilocuquejo@gmail.com', NULL, '19b35c4f-28d4-487f-8c60-37717385a41e', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (33, 'E. E. M. Carmem Menezes Direito', 'CLAUDIA REGINA DE LIMA SANTIAGO', 'Rua Manoel Araújo dos Santos, nº 1043 - Brisamar - Itaguaí/RJ - CEP: 23825-435', '21 96425-1829', 'eem.carmemmenezesdireito@edu.itaguai.rj.gov.br carmem.menezes.adm@gmail.com', NULL, 'df6272f1-4cfa-42af-b9aa-f61dcbcbbe1a', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (34, 'E. E. M. Chaperó', 'THAIS SILVA DE SOUZA', 'Rua Dezesseis, s/n (Gleba B) - Chaperó - Itaguaí/RJ - CEP: 23835-000', '21 99499-1646', 'eem.chapero@edu.itaguai.rj.gov.br', NULL, '536e89e8-ea1c-4a30-83e7-006490a5c304', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (35, 'E. E. M. Fazenda Santa Cândida', 'ANA CRISTINA BORGES DE SANTANA', 'Rua Altamiro Domiciano da Cruz, s/n - Santa Cândida - Itaguaí/RJ - CEP: 23830-640', '21 96573-1339', 'eem.fazsantacandida@edu.itaguai.rj.gov.br', NULL, '8c2ed8c0-0e78-43ba-bb4f-a7859805cc20', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (36, 'E. E. M. Mazomba - Dr. Jorge Abrahão', 'FERNANDA LIMA FELICIANO PINTO', 'Estrada do Mazomba, nº 22 - Mazomba - Itaguaí/RJ - CEP: 23830-250', '21 96436-0626', 'eem.drjorgeabrahao@edu.itaguai.rj.gov.br', NULL, '56d9b8b3-48bf-4c58-beb9-f247c14cea5e', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (37, 'E. E. M. Santa Rosa', 'MARLI DOS SANTOS FERNANDES', 'Estrada Santa Rosa, nº 2587 - Santa Rosa - Itaguaí/RJ - CEP: 23855-205', '21 99690-6262', 'eem.santarosa@edu.itaguai.rj.gov.br', NULL, 'a0b20bb8-a32a-43a8-be6a-23c28fb0506f', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (38, 'E. E. M. Taciano Basílio', 'DAYSE ADRIANA SODRE GONCALVES', 'Estr.Bom Jardim, nº 953 ((Estr. Caçador)) - Saco da Prata - Itaguaí/RJ - CEP: 23835-700', '21 97471-8656', 'eem.tacianobasilio@edu.itaguai.rj.gov.br', NULL, '13a13a48-b76b-4235-87d2-b825917dac3a', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (39, 'E. M. Alexandre Ignácio', 'SANDRA DIAS PIMENTA DA SILVA', 'Estrada do Caçador, s/n - Ibituporanga - Itaguaí/RJ - CEP: 23835-090', '21 97060-1512', 'em.alexandreignacio@edu.itaguai.rj.gov.br', NULL, '073ab9da-0276-45ff-8ab6-072c8dce1567', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (40, 'E. M. Amauri Ferreira', 'ILONIA MARCIA DE MIRANDA PAULO', 'Rua Guilherme Serrano, s/n - Vila Geny - Itaguaí/RJ - CEP: 23825-480', '21 97360-1960', 'em.amauriferreira@edu.itaguai.rj.gov.br', NULL, 'a2d22cfe-e258-43de-bf95-7d1626db9a7a', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (41, 'E. M. Antônio Tupinambá', 'MONICA DE LIMA DRUMOND', 'Rua Júlio Verne,, s/n - Vila Margarida - Itaguaí/RJ - CEP: 23820-770', '(21) 99101-6799', 'em.antoniotupinamba@edu.itaguai.rj.gov.br', NULL, '65a98c71-580e-45dc-b5c2-08a9940b4cdc', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (42, 'E. M. Argentina Coutinho', 'JULIANA AVILEZ', 'Rua Pedro Pacheco, s/n - Brisamar - Itaguaí/RJ - CEP: 23825-205', '21 98063-3998', 'em.argentinacoutinho@edu.itaguai.rj.gov.br', NULL, '0022776c-f85f-4b2b-b6a1-e95dca34c2aa', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (43, 'E. M. Coronel Alziro Santiago', 'ROBERTA OLIVEIRA DA SILVA GALDINO', 'Estrada do Mazomba, s/n - Mazomba - Itaguaí/RJ - CEP: 23830-250', '21 97012-4395', 'em.celalzirosantiago@edu.itaguai.rj.gov.br', NULL, '15ac96a0-1a7b-40cf-ad46-a8380dc60a78', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (44, 'E. M. das Acácias', 'CAMILA LOPES SABINO FONSECA', 'Rua das Camélias,, s/n (Qd 131) - Parque Primavera - Itaguaí/RJ - CEP: 23830-395', '21 99295-4593', 'em.acacias@edu.itaguai.rj.gov.br', NULL, 'b8590fd5-1050-4a04-8632-c4db93d8ddd3', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (45, 'E. M. de Educação Infantil Hypolito Vieira de Carvalho', 'SONIA ISABEL VALENTIM COSTA MACHADO', 'Rua Estados Unidos, nº 66 - Jardim América - Itaguaí/RJ - CEP: 23810-100', '21 97633-6683', 'emei.hypolitovieradecarvalho@edu.itaguai.rj.gov.br', NULL, '61345a18-800e-49d3-8395-e0be1f6d4853', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (46, 'E. M. de Educação Infantil Monteiro Lobato', 'DÉBORA DOMINGOS CARNEIRO', 'Rua Kaisser Abraão, nº 9 - Mont Serrat - Itaguaí/RJ - CEP: 23810-560', '21 98062-0658', 'emei.monteirolobato@edu.itaguai.rj.gov.br', NULL, 'a4bcd7be-709f-41f4-8884-cf5b8f2279df', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (47, 'E. M. de Educação Infantil Pref. Isoldackson Cruz de Brito', 'Marinalda de Lima Lemes', 'Rua Dezesseis, nº 180 (Bleba B) - Gleba B - Chaperó - Itaguaí/RJ - CEP: 23812-285', '(21) 99226-8412', 'emei.prefisoldacksoncruzdebrito@edu.itaguai.rj.gov.br', NULL, '73f6df36-8765-40c3-acc5-dbdbd7c27aca', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (48, 'E. M. Eider Ribeiro Dantas', 'JOSENI DE SOUZA BARRETO BARBOSA', 'Rua Argentina da Silva Coutinho, s/n (Lote 11 - Qd 52) - Brisamar - Itaguaí/RJ - CEP: 23825-210', '21 96667-0417', 'em.eiderribeirodantas@edu.itaguai.rj.gov.br', NULL, 'bd92c0ea-d8ec-4e8f-9d5d-33016e3e940f', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (49, 'E. M. Elmira Figueira', 'SONIA REGINA SILVA DE OLIVEIRA BARBOSA', 'Rua Tocantins, s/n - Estrela do Céu - Itaguaí/RJ - CEP: 23815-180', '21 96465-2372', 'em.elmirafigueira@edu.itaguai.rj.gov.br', NULL, '13501024-7e2f-4272-aa62-b83142002314', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (50, 'E. M. Elmo Baptista Coelho', 'DANNUBIA', 'Est Joaquim Fernandes, nº 407/409 - Ilha da Madeira - Itaguaí/RJ - CEP: 23821-450', '(21) 98228-8351', 'em.elmobaptistacoelho@edu.itaguai.rj.gov.br', NULL, 'a5d3e651-627b-4503-b55f-f55a73a334d1', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (51, 'E. M. Fusao Fukamati', 'KILSA CRISTINA ARANTES GONCALVES SILVA', 'Rua Dezoito, s/n (Quadra 18, Gleba A) - Chaperó - Itaguaí/RJ - CEP: 23835-000', '21 99359-1145', 'em.fusaofukmati@edu.itaguai.gov.br', NULL, '65a45236-8c51-4d8f-9eae-d8e97de66950', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (52, 'E. M. Jorge Flores da Silva', 'LEANDRO FERREIRA', 'Rua Ary Parreira esquina com Estrada do Tronco, s/n - Weda - Itaguaí/RJ - CEP: 23820-303', '21 98711-9622', 'em.jorgefloresdasilva@edu.itaguai.rj.gov.br', NULL, '7083e4b9-43e5-48b2-9664-0255d9d5528d', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (53, 'E. M. Padre Rafael Scarfó', 'LILIAN KELLY AMARAL DE SOUZA EUGENIO', 'Rua Elvira Ciuffo Cicarino, nº 40 - Vila Margarida - Itaguaí/RJ - CEP: 23821-135', '21 96415-3882', 'em.padrerafaelscarfo@edu.itaguai.rj.gov.br', NULL, '1a585773-7d2d-439f-88d9-0b8fd1b23b75', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (54, 'E. M. Prefeito Abeilard Goulart de Souza', 'DAYANE LIMA FELICIANO PINTO', 'R. Jonas Costa Pereira, s/n - Parque Paraíso - Itaguaí/RJ - CEP: 23815-100', '21 98657-6449', 'em.prefalbeilardgoulartdesouza@edu.itaguai.rj.gov.br', NULL, 'd44b44d7-503b-4e38-94cf-d8b3f44f3b06', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (55, 'E. M. Prefeito Wilson Pedro Francisco', 'IVANETE FERREIRA DE SIQUEIRA', 'Estrada do Teixeira, s/n (lote 25, Quadra 06) - Vista Alegre - Itaguaí/RJ - CEP: 23820-275', '21 98288-3163', 'em.prefwilsonpedrofrancisco@edu.itaguai.rj.gov.br', NULL, '6be9001d-16d8-4249-8bb8-77eefbc6b788', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (56, 'E. M. Prof.ª Maria Guilhermina de Souza Farias', 'THAIS RIBEIRO CORREA PINTO', 'Estrada Engenheiro Ivan Mundin, s/n - Leandro - Itaguaí/RJ - CEP: 23830-250', '21 96474-6039', 'em.mariaguilherminadesouzafreire@edu.itaguai.rj.gov.br', NULL, '4e4fb381-5582-4f04-8a09-6f7e27e446d1', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (57, 'E. M. Prof.ª Severina dos Ramos de Sousa', 'FLAVIO COSME ROCHA DE LIMA', 'Rua Evelina Reis e Geny Reis, s/n (Lotes 25, 26 e 27) - Vila Geny - Itaguaí/RJ - CEP: 23825-350', '21 96467-1717', 'em.severinadosramosdesousa@edu.itaguai.rj.gov.br', NULL, '1e348461-0da0-4b59-a14f-db42af063503', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (58, 'E. M. Prof.ª Yolanda Rangel Pereira', 'MARGARETH FERREIRA', 'Rua Francisco Costa Pereira, s/n - Engenho - Itaguaí/RJ - CEP: 23820-240', '21 98650-4463', 'em.yolandarangelpereira@edu.itaguai.rj.gov.br', NULL, 'a2c2a3e9-97d5-4466-8f40-f92a10bc4d09', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (59, 'E. M. Profª. Marianilde Siqueira Gonçalves', 'SANDRO CORRÊA', 'Rua Capitao Landulfo Alves de Almeida, s/n (Qd39) - Jardim Mar - Itaguaí/RJ - CEP: 23823-000', '21 97033-4403', 'em.jardimmar@edu.itaguai.rj.gov.br', NULL, '0f5c41ee-9227-4cea-89d8-b8eb6310c61c', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (60, 'E. M. Renato Gonçalves Martins', 'Lusmar Moraes Barbosa', 'Est. Jose Paulo Andrade, nº 2584 - Chaperó - Itaguaí/RJ - CEP: 23855-120', '(21) 97581-1877', 'em.renatogoncalvesmartins@edu.itaguai.rj.gov.br', NULL, '0f1883eb-8814-42d5-8d50-51476a67dd14', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (61, 'E. M. Severino Salustiano de Freitas', 'INA DANIELA DE OLIVEIRA TAMAKI', 'Rua Genecildo A Vieira, s/n (esquina com Rua 2) - Teixeira - Itaguaí/RJ - CEP: 23820-270', '21 97579-5737', 'em.severinosalustianodefrarias@edu.itaguai.rj.gov.br', NULL, '5be3e450-d3a7-4763-b191-83f5629ec59f', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (62, 'E. M. Sylvia Souza Siquineli', 'ROGERIA TAVARES', 'Estr. Décio Muniz da Silva Filho, nº 1006 (, Lagoa Nova, Gleba B) - Chaperó - Itaguaí/RJ - CEP: 23831-300', '21 99103-3333', NULL, NULL, 'f4d35649-c605-42f1-8ead-59255f76d752', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (63, 'E. M. São Sebastião', 'MARINALVA DOS SANTOS CONDE', 'Estr. Zeferino Goulart, s/n - Raiz da Serra - Itaguaí/RJ - CEP: 23830-000', '21 98819-5235', 'em.saosebastiao@edu.itaguai.rj.gov.br', NULL, '5a7eaffb-e3e0-4772-8b1e-ecdec8d3c146', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (64, 'E. M. Tereza de Araújo Sagário', 'DAYANE RODRIGUES DA CONCEIÇÃO MOURA', 'Av. Tabajara, s/n - Ibirapitanga - Itaguaí/RJ - CEP: 23812-150', '21 97514-0994', 'em.terezadearaujosagario@edu.itaguai.rj.gov.br', NULL, '928521e6-e869-425f-88fb-0e4d939767fd', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (66, 'E. M. Vereador Américo Rodrigues de Amorim', 'Luciane Leal do Valle', 'R Sebastião Bruno de Oliveira, s/n - Itimirim - Itaguaí/RJ - CEP: 23826-320', '(21) 99228-3003', 'em.veramericorodriguesdeamorim@edu.itaguai.rj.gov.br', NULL, '8782b024-8651-4a01-85af-9118a2d8f488', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (67, 'E. M. Vereador José Galliaço Prata', 'MARCELO DONIZETE DE BARROS', 'Estrada do Teixeira, s/n - Amendoeira - Itaguaí/RJ - CEP: 23820-275', '21 99374-4482', 'em.vereadorgalliacoprata@edu.itaguai.rj.gov.br', NULL, 'a3622b18-9a09-4536-b9c1-0a1d3d79c010', NULL, NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.schools ("id", "name", "director", "address", "phone", "email", "code", "external_id", "lat", "lon", "active") VALUES (68, 'E. M. Vereador Taciano Fernandes Nunes', 'ROSINEIA ALVES BATISTA', 'Av. Gov. Mario Covas, nº 36 - Brisamar - Itaguaí/RJ - CEP: 23826-240', '21 96415-4572', 'em.vertaianofernandesnunes@edu.itaguai.rj.gov.br', NULL, 'c51e906f-a897-4134-8918-eb4183875c1e', NULL, NULL, 1) ON CONFLICT DO NOTHING;

-- Inserindo 3 registro(s) em users
INSERT INTO public.users ("id", "name", "email", "password_hash", "role", "school_id", "active") VALUES (1, 'Gestor da Infraestrutura', 'gestor@agenda.local', '91e6745512f60d77cf0ea2f7c475dd53$fd7c7f784e1d20f29219e8ce7a68a301cb0e580be97eac506066d1679221e328', 'gestor', NULL, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.users ("id", "name", "email", "password_hash", "role", "school_id", "active") VALUES (2, 'Direção Escolar', 'escola@agenda.local', '0b2319dbda0872a891598c87e179da28$7a9c6074da8d1df06b1a9cc166477d87baf8462a6c28722a92e38939d52f1d1b', 'escola', 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.users ("id", "name", "email", "password_hash", "role", "school_id", "active") VALUES (3, 'Equipe de Planejamento', 'planejamento@agenda.local', '8bd2124b2f594584ed88fa0d157d77c5$0c2ce4de8b070a1c3fd9f2e3a604c97ce61350d9716a3c9f15a1c8632f71ae12', 'planejamento', NULL, 1) ON CONFLICT DO NOTHING;

-- Inserindo 3 registro(s) em access_profiles
INSERT INTO public.access_profiles ("id", "slug", "label", "description", "school_scoped", "can_edit_analysis", "can_manage_admin", "can_view_reports", "can_view_planning", "is_system", "active", "created_at") VALUES (1, 'gestor', 'Gestor da Infraestrutura', 'Visão completa, análise técnica, priorização, relatórios e administração.', 0, 1, 1, 1, 1, 1, 1, '2026-08-29 10:32:20') ON CONFLICT DO NOTHING;
INSERT INTO public.access_profiles ("id", "slug", "label", "description", "school_scoped", "can_edit_analysis", "can_manage_admin", "can_view_reports", "can_view_planning", "is_system", "active", "created_at") VALUES (2, 'escola', 'Unidade Escolar', 'Cadastro e acompanhamento das demandas da própria unidade.', 1, 0, 0, 0, 0, 1, 1, '2026-08-29 10:32:20') ON CONFLICT DO NOTHING;
INSERT INTO public.access_profiles ("id", "slug", "label", "description", "school_scoped", "can_edit_analysis", "can_manage_admin", "can_view_reports", "can_view_planning", "is_system", "active", "created_at") VALUES (3, 'planejamento', 'Planejamento', 'Consolidação de demandas futuras, exercícios e planejamento orçamentário.', 0, 1, 0, 1, 1, 1, 1, '2026-08-29 10:32:20') ON CONFLICT DO NOTHING;

-- Inserindo 67 registro(s) em categories
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (1, 'Elétrica', 'bolt', 'red', 'Fiação, tomada, quadro de força, curto-circuito', 0, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (2, 'Hidráulica', 'drop', 'orange', 'Vazamento, entupimento, cano estourado', 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (3, 'Cobertura/Telhado', 'roof', 'teal', 'Goteira, infiltração, telha quebrada', 2, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (4, 'Pintura', 'paint', 'violet', 'Parede descascando, mofo, pintura antiga', 3, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (5, 'Climatização', 'wind', 'green', 'Ventilador ou ar-condicionado com problema', 4, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (6, 'Serralheria', 'wrench', 'blue', 'Portão, grade ou trava com defeito', 5, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (7, 'Alvenaria', 'brick', 'red', 'Rachadura, muro ou parede danificada', 6, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (8, 'Acessibilidade', 'wheelchair', 'orange', 'Rampa, corrimão, piso tátil', 7, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (9, 'Mobiliário', 'chair', 'teal', 'Mesa, cadeira, armário quebrado', 8, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (10, 'Equipamentos', 'monitor', 'violet', 'Computador, projetor, equipamento com defeito', 9, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (11, 'Segurança', 'shield', 'green', 'Câmera, alarme, iluminação de segurança', 10, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (12, 'Saneamento', 'drain', 'blue', 'Esgoto, caixa de gordura, fossa', 11, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (13, 'Estrutura', 'column', 'red', 'Coluna, viga, laje ou base comprometida', 12, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (14, 'Área externa', 'tree', 'orange', 'Quadra, pátio, jardim, área externa', 13, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (15, 'Iluminação', 'bulb', 'teal', 'Lâmpada queimada, poste ou luminária', 14, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (16, 'Portas e janelas', 'door', 'violet', 'Porta ou janela emperrada, vidro quebrado', 15, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (17, 'Reforma', 'hammer', 'green', 'Melhoria ou reparo de maior porte', 16, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (18, 'Obra', 'crane', 'blue', 'Construção ou ampliação', 17, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (19, 'Aquisição', 'cart', 'red', 'Compra de material ou equipamento novo', 18, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (20, 'Outros', 'dots', 'orange', 'Não se encaixa nas opções acima', 19, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (21, 'Agendamento', 'calendar', 'red', 'Marcação de data para visita, vistoria ou serviço', 20, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (22, 'Assistência', 'message', 'orange', 'Suporte técnico ou apoio pontual à unidade', 21, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (23, 'Automação', 'settings', 'teal', 'Portões, sistemas e equipamentos automatizados', 22, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (24, 'Avaliação', 'report', 'violet', 'Laudo técnico ou parecer sobre uma condição', 23, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (25, 'Boletim de Ocorrência', 'file', 'green', 'Registro policial de furto, dano ou ocorrência', 24, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (26, 'Bombeiro Hidráulico', 'wrench', 'blue', 'Serviço de encanador para reparos hidráulicos', 25, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (27, 'Capina', 'tree', 'red', 'Corte de mato e limpeza de área externa', 26, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (28, 'Comunicado', 'message', 'orange', 'Aviso ou comunicação oficial à unidade', 27, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (29, 'Conserto', 'wrench', 'teal', 'Reparo pontual de item ou equipamento', 28, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (30, 'Consultoria', 'report', 'violet', 'Orientação técnica especializada', 29, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (31, 'Conta Luz', 'money', 'green', 'Fatura ou pendência de energia elétrica', 30, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (32, 'Corte', 'warning', 'blue', 'Corte de fornecimento (energia, água ou similar) por pendência', 31, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (33, 'Declaração', 'file', 'red', 'Emissão de declaração ou documento oficial', 32, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (34, 'Dedetização', 'shield', 'orange', 'Controle de insetos e pragas urbanas', 33, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (35, 'Desratização', 'shield', 'teal', 'Controle de roedores', 34, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (36, 'Desalojamento de pombos', 'shield', 'violet', 'Remoção e controle de pombos', 35, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (37, 'Desinfecção', 'shield', 'green', 'Higienização e desinfecção de ambientes', 36, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (38, 'Iluminação Interna', 'bulb', 'blue', 'Lâmpada ou luminária de ambientes internos', 37, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (39, 'Iluminação Externa', 'bulb', 'red', 'Iluminação de pátio, quadra ou área externa', 38, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (40, 'Informação', 'message', 'orange', 'Pedido de esclarecimento ou informação', 39, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (41, 'Inspeção', 'report', 'teal', 'Inspeção técnica geral', 40, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (42, 'Inspeção Gás', 'warning', 'violet', 'Inspeção de rede ou botijão de gás', 41, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (43, 'Instalação', 'wrench', 'green', 'Instalação de novo item ou equipamento', 42, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (44, 'Isolamento', 'warning', 'blue', 'Isolamento de área por risco ou obra', 43, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (45, 'Jardinagem', 'tree', 'red', 'Manutenção de jardins e áreas verdes', 44, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (46, 'Levantamento', 'report', 'orange', 'Levantamento técnico ou de quantidades', 45, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (47, 'Limpeza', 'drop', 'teal', 'Limpeza geral de ambientes ou área', 46, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (48, 'Manutenção', 'wrench', 'violet', 'Manutenção preventiva ou corretiva geral', 47, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (49, 'Montagem', 'hammer', 'green', 'Montagem de móveis, estruturas ou equipamentos', 48, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (50, 'Obra/Reparo', 'crane', 'blue', 'Obra ou reparo de maior porte', 49, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (51, 'Poda de árvore', 'tree', 'red', 'Corte ou poda de árvore específica', 50, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (52, 'Poda e Roçada', 'tree', 'orange', 'Poda e roçada de área externa', 51, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (53, 'Reciclagem', 'cart', 'teal', 'Descarte ou coleta seletiva de resíduos', 52, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (54, 'Refrigeração', 'wind', 'violet', 'Geladeira, freezer ou sistema de refrigeração', 53, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (55, 'Relatório', 'report', 'green', 'Elaboração ou solicitação de relatório', 54, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (56, 'Reparo', 'wrench', 'blue', 'Reparo geral não especificado', 55, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (57, 'Resposta', 'message', 'red', 'Resposta a ofício, e-mail ou solicitação', 56, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (58, 'Retirada', 'cart', 'orange', 'Retirada de material, entulho ou equipamento', 57, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (59, 'Retorno', 'trend', 'teal', 'Retorno sobre solicitação ou atendimento anterior', 58, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (60, 'Serviço de solda', 'bolt', 'violet', 'Solda de grades, portões ou estruturas metálicas', 59, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (61, 'Solicitação', 'clipboard', 'green', 'Pedido geral de serviço ou material', 60, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (62, 'Substituição', 'wrench', 'blue', 'Troca de peça, item ou equipamento danificado', 61, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (63, 'Transporte', 'cart', 'red', 'Transporte de material, equipamento ou pessoas', 62, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (64, 'Troca', 'cart', 'orange', 'Troca de peça, produto ou equipamento', 63, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (65, 'Vacall', 'drop', 'teal', 'Caminhão limpa-fossa (sucção de esgoto)', 64, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (66, 'Visita técnica', 'school', 'violet', 'Visita para avaliação presencial no local', 65, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.categories ("id", "name", "icon", "color", "hint", "sort_order", "active") VALUES (67, 'Vistoria', 'camera', 'green', 'Vistoria e registro fotográfico das condições', 66, 1) ON CONFLICT DO NOTHING;

-- Inserindo 4 registro(s) em priority_levels
INSERT INTO public.priority_levels ("id", "code", "label", "hint", "color", "rank") VALUES (1, 'P1', 'Urgente', 'Risco agora ou impede a aula', 'red', 1) ON CONFLICT DO NOTHING;
INSERT INTO public.priority_levels ("id", "code", "label", "hint", "color", "rank") VALUES (2, 'P2', 'Alta', 'Já incomoda a rotina da escola', 'orange', 2) ON CONFLICT DO NOTHING;
INSERT INTO public.priority_levels ("id", "code", "label", "hint", "color", "rank") VALUES (3, 'P3', 'Programada', 'Não atrapalha o dia a dia agora', 'blue', 3) ON CONFLICT DO NOTHING;
INSERT INTO public.priority_levels ("id", "code", "label", "hint", "color", "rank") VALUES (4, 'P4', 'Planejamento/Projeto', 'Reservada para um exercício futuro', 'green', 4) ON CONFLICT DO NOTHING;

-- Inserindo 7 registro(s) em kanban_stages
INSERT INTO public.kanban_stages ("id", "stage_key", "label", "hint", "accent", "statuses", "target_status", "sort_order") VALUES (1, 'novas', 'Novas', 'Acabaram de chegar, ainda sem triagem', 'blue', '["Nova", "Recebida"]', 'Recebida', 0) ON CONFLICT DO NOTHING;
INSERT INTO public.kanban_stages ("id", "stage_key", "label", "hint", "accent", "statuses", "target_status", "sort_order") VALUES (2, 'analise', 'Em Análise', 'Triagem, avaliação técnica ou visita agendada', 'orange', '["Em triagem", "Em análise técnica", "Aguardando informações da escola", "Visita técnica agendada"]', 'Em análise técnica', 1) ON CONFLICT DO NOTHING;
INSERT INTO public.kanban_stages ("id", "stage_key", "label", "hint", "accent", "statuses", "target_status", "sort_order") VALUES (3, 'aguardando', 'Aguardando', 'Depende de material, orçamento, contratação ou outro setor', 'violet', '["Em planejamento", "Aguardando material", "Aguardando orçamento", "Aguardando contratação", "Aguardando empresa", "Encaminhada para outro setor", "Reprogramada"]', 'Aguardando contratação', 2) ON CONFLICT DO NOTHING;
INSERT INTO public.kanban_stages ("id", "stage_key", "label", "hint", "accent", "statuses", "target_status", "sort_order") VALUES (4, 'execucao', 'Em Execução', 'Serviço programado ou em andamento', 'teal', '["Serviço programado", "Em execução", "Parcialmente executada"]', 'Em execução', 3) ON CONFLICT DO NOTHING;
INSERT INTO public.kanban_stages ("id", "stage_key", "label", "hint", "accent", "statuses", "target_status", "sort_order") VALUES (5, 'futuro', 'Planejamento Futuro', 'Reservada para um exercício futuro', 'blue', '["Planejamento futuro"]', 'Planejamento futuro', 4) ON CONFLICT DO NOTHING;
INSERT INTO public.kanban_stages ("id", "stage_key", "label", "hint", "accent", "statuses", "target_status", "sort_order") VALUES (6, 'concluida', 'Concluída', 'Atendimento finalizado', 'green', '["Concluída"]', 'Concluída', 5) ON CONFLICT DO NOTHING;
INSERT INTO public.kanban_stages ("id", "stage_key", "label", "hint", "accent", "statuses", "target_status", "sort_order") VALUES (7, 'cancelada', 'Cancelada', 'Encerrada sem execução', 'red', '["Cancelada"]', 'Cancelada', 6) ON CONFLICT DO NOTHING;

-- Inserindo 11 registro(s) em demands
INSERT INTO public.demands ("id", "code", "title", "description", "category", "subcategory", "location", "impact", "affected_people", "risk", "blocks_activity", "school_id", "priority", "status", "created_at", "updated_at", "due_date", "responsible", "sector", "cost_estimate", "action_defined", "technical_opinion", "dependencies", "needs_visit", "needs_budget", "needs_material", "needs_contract", "future_year", "planning_kind", "planned_quantity", "planned_unit", "created_by", "prov_description", "prov_action_type", "prov_responsible", "prov_due_date", "prov_priority", "prov_note", "prov_notify_school") VALUES (1, 'INF-2026-00001', 'Reparo de infiltração no telhado — Bloco B', 'Infiltração intensa em duas salas durante períodos de chuva, com risco de dano ao forro e interrupção das aulas.', 'Cobertura/Telhado', NULL, 'Sala 3 / Bloco B', 'Risco à estrutura e às atividades pedagógicas', 64, 1, 1, 1, 'P1', 'Em execução', '2026-08-12 00:48:11', '2026-08-29 02:50:16', '2026-09-03', 'Equipe de manutenção predial', 'Infraestrutura', NULL, 'Reparo emergencial da cobertura e impermeabilização', 'Vistoria confirmou falha na membrana de impermeabilização.', 'Compra pontual de manta e agendamento da equipe', 1, 1, 1, 0, NULL, NULL, 0.0, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, 0) ON CONFLICT DO NOTHING;
INSERT INTO public.demands ("id", "code", "title", "description", "category", "subcategory", "location", "impact", "affected_people", "risk", "blocks_activity", "school_id", "priority", "status", "created_at", "updated_at", "due_date", "responsible", "sector", "cost_estimate", "action_defined", "technical_opinion", "dependencies", "needs_visit", "needs_budget", "needs_material", "needs_contract", "future_year", "planning_kind", "planned_quantity", "planned_unit", "created_by", "prov_description", "prov_action_type", "prov_responsible", "prov_due_date", "prov_priority", "prov_note", "prov_notify_school") VALUES (2, 'INF-2026-00002', 'Substituição da trava do portão principal', 'Trava do portão principal danificada, dificultando o controle seguro do acesso à unidade.', 'Serralheria', NULL, 'Portão principal', 'Impacto direto na segurança do acesso', 420, 1, 0, 4, 'P2', 'Em análise técnica', '2026-08-13 00:48:11', '2026-08-29 09:37:24', '2026-09-08', 'Empresa terceirizada', 'Infraestrutura', 3200.0, 'Substituição da fechadura e reforço da estrutura', 'Necessária contratação de serralheria.', 'Contratação de empresa especializada', 0, 1, 1, 1, NULL, NULL, 0.0, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, 0) ON CONFLICT DO NOTHING;
INSERT INTO public.demands ("id", "code", "title", "description", "category", "subcategory", "location", "impact", "affected_people", "risk", "blocks_activity", "school_id", "priority", "status", "created_at", "updated_at", "due_date", "responsible", "sector", "cost_estimate", "action_defined", "technical_opinion", "dependencies", "needs_visit", "needs_budget", "needs_material", "needs_contract", "future_year", "planning_kind", "planned_quantity", "planned_unit", "created_by", "prov_description", "prov_action_type", "prov_responsible", "prov_due_date", "prov_priority", "prov_note", "prov_notify_school") VALUES (3, 'INF-2026-00003', 'Pintura das salas de aula', 'Paredes com desgaste de pintura e marcas de umidade já sanadas.', 'Pintura', NULL, 'Bloco pedagógico', 'Melhoria do ambiente escolar', 280, 0, 0, 2, 'P3', 'Serviço programado', '2026-08-14 00:48:11', '2026-08-14 00:48:11', '2026-10-03', 'Equipe de manutenção', 'Infraestrutura', 9800.0, 'Pintura prevista para o próximo recesso', 'Serviço pode ser executado sem urgência.', 'Recesso escolar', 0, 1, 1, 0, NULL, NULL, 0.0, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, 0) ON CONFLICT DO NOTHING;
INSERT INTO public.demands ("id", "code", "title", "description", "category", "subcategory", "location", "impact", "affected_people", "risk", "blocks_activity", "school_id", "priority", "status", "created_at", "updated_at", "due_date", "responsible", "sector", "cost_estimate", "action_defined", "technical_opinion", "dependencies", "needs_visit", "needs_budget", "needs_material", "needs_contract", "future_year", "planning_kind", "planned_quantity", "planned_unit", "created_by", "prov_description", "prov_action_type", "prov_responsible", "prov_due_date", "prov_priority", "prov_note", "prov_notify_school") VALUES (4, 'INF-2026-00004', 'Construção de rampa de acessibilidade', 'Adequação do acesso ao refeitório para garantir acessibilidade.', 'Acessibilidade', NULL, 'Acesso ao refeitório', 'Acessibilidade e inclusão', 45, 0, 0, 3, 'P4', 'Planejamento futuro', '2026-08-15 00:48:11', '2026-08-15 00:48:11', '2027-02-25', 'Equipe de projetos', 'Planejamento', 78000.0, 'Elaboração de projeto e contratação futura', 'Demanda requer projeto executivo e previsão orçamentária.', 'Projeto, orçamento e licitação', 1, 1, 1, 1, 2027, NULL, 0.0, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, 0) ON CONFLICT DO NOTHING;
INSERT INTO public.demands ("id", "code", "title", "description", "category", "subcategory", "location", "impact", "affected_people", "risk", "blocks_activity", "school_id", "priority", "status", "created_at", "updated_at", "due_date", "responsible", "sector", "cost_estimate", "action_defined", "technical_opinion", "dependencies", "needs_visit", "needs_budget", "needs_material", "needs_contract", "future_year", "planning_kind", "planned_quantity", "planned_unit", "created_by", "prov_description", "prov_action_type", "prov_responsible", "prov_due_date", "prov_priority", "prov_note", "prov_notify_school") VALUES (5, 'INF-2026-00005', 'Revisão do quadro elétrico', 'Quadro elétrico apresenta aquecimento em períodos de maior consumo.', 'Elétrica', NULL, 'Cozinha', 'Risco operacional e possível interrupção', 75, 1, 1, 5, 'P1', 'Aguardando contratação', '2026-08-16 00:48:11', '2026-08-30 19:13:47', '2026-09-01', 'Engenharia elétrica', 'Infraestrutura', 12000.0, '', 'Aguardando medição de carga.', 'Visita técnica especializada', 1, 1, 0, 0, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, 0) ON CONFLICT DO NOTHING;
INSERT INTO public.demands ("id", "code", "title", "description", "category", "subcategory", "location", "impact", "affected_people", "risk", "blocks_activity", "school_id", "priority", "status", "created_at", "updated_at", "due_date", "responsible", "sector", "cost_estimate", "action_defined", "technical_opinion", "dependencies", "needs_visit", "needs_budget", "needs_material", "needs_contract", "future_year", "planning_kind", "planned_quantity", "planned_unit", "created_by", "prov_description", "prov_action_type", "prov_responsible", "prov_due_date", "prov_priority", "prov_note", "prov_notify_school") VALUES (6, 'INF-2026-00006', 'Aquisição de aparelhos de ar-condicionado', 'Necessidade de renovação de equipamentos antigos e inoperantes.', 'Climatização', NULL, 'Salas de aula', 'Conforto térmico e continuidade das atividades', 310, 0, 0, 6, 'P4', 'Planejamento futuro', '2026-08-17 00:48:11', '2026-08-30 18:37:10', '2027-04-06', 'Planejamento de compras', 'Planejamento', 144000.0, 'Consolidar com demandas de outras unidades para licitação', 'Demanda adequada para aquisição consolidada.', 'Planejamento orçamentário e licitação', 0, 1, 1, 1, 2027, NULL, 0.0, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, 0) ON CONFLICT DO NOTHING;
INSERT INTO public.demands ("id", "code", "title", "description", "category", "subcategory", "location", "impact", "affected_people", "risk", "blocks_activity", "school_id", "priority", "status", "created_at", "updated_at", "due_date", "responsible", "sector", "cost_estimate", "action_defined", "technical_opinion", "dependencies", "needs_visit", "needs_budget", "needs_material", "needs_contract", "future_year", "planning_kind", "planned_quantity", "planned_unit", "created_by", "prov_description", "prov_action_type", "prov_responsible", "prov_due_date", "prov_priority", "prov_note", "prov_notify_school") VALUES (7, 'INF-2026-00007', 'Reparo de vazamento na cozinha', 'Vazamento contínuo sob pia industrial, causando acúmulo de água.', 'Hidráulica', NULL, 'Cozinha', 'Risco de queda e prejuízo à rotina da alimentação escolar', 35, 1, 1, 1, 'P2', 'Concluída', '2026-08-18 00:48:11', '2026-08-18 00:48:11', '2026-08-27', 'Equipe hidráulica', 'Infraestrutura', 950.0, 'Troca de conexão e vedação', 'Atendimento concluído e validado pela direção.', '', 0, 0, 1, 0, NULL, NULL, 0.0, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, 0) ON CONFLICT DO NOTHING;
INSERT INTO public.demands ("id", "code", "title", "description", "category", "subcategory", "location", "impact", "affected_people", "risk", "blocks_activity", "school_id", "priority", "status", "created_at", "updated_at", "due_date", "responsible", "sector", "cost_estimate", "action_defined", "technical_opinion", "dependencies", "needs_visit", "needs_budget", "needs_material", "needs_contract", "future_year", "planning_kind", "planned_quantity", "planned_unit", "created_by", "prov_description", "prov_action_type", "prov_responsible", "prov_due_date", "prov_priority", "prov_note", "prov_notify_school") VALUES (8, 'INF-2026-00008', 'Recomposição do muro lateral', 'Trecho de muro apresenta fissuras e pontos de desprendimento.', 'Estrutura', NULL, 'Limite lateral', 'Segurança patrimonial', 190, 1, 0, 2, 'P2', 'Em análise técnica', '2026-08-19 00:48:11', '2026-08-29 09:37:20', '2026-08-25', 'Equipe de obras', 'Infraestrutura', 28000.0, 'Escoramento preventivo e recomposição', 'Prazo reprogramado por indisponibilidade de material.', 'Material específico', 1, 1, 1, 0, NULL, NULL, 0.0, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, 0) ON CONFLICT DO NOTHING;
INSERT INTO public.demands ("id", "code", "title", "description", "category", "subcategory", "location", "impact", "affected_people", "risk", "blocks_activity", "school_id", "priority", "status", "created_at", "updated_at", "due_date", "responsible", "sector", "cost_estimate", "action_defined", "technical_opinion", "dependencies", "needs_visit", "needs_budget", "needs_material", "needs_contract", "future_year", "planning_kind", "planned_quantity", "planned_unit", "created_by", "prov_description", "prov_action_type", "prov_responsible", "prov_due_date", "prov_priority", "prov_note", "prov_notify_school") VALUES (9, 'INF-2026-00009', 'Iluminação — banheiro', 'queimada', 'Iluminação', NULL, 'banheiro', NULL, 30, 0, 0, 2, 'P3', 'Nova', '2026-08-29 01:01:38', '2026-08-29 01:01:38', NULL, NULL, NULL, 0.0, NULL, NULL, NULL, 0, 0, 0, 0, NULL, NULL, 0.0, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, 0) ON CONFLICT DO NOTHING;
INSERT INTO public.demands ("id", "code", "title", "description", "category", "subcategory", "location", "impact", "affected_people", "risk", "blocks_activity", "school_id", "priority", "status", "created_at", "updated_at", "due_date", "responsible", "sector", "cost_estimate", "action_defined", "technical_opinion", "dependencies", "needs_visit", "needs_budget", "needs_material", "needs_contract", "future_year", "planning_kind", "planned_quantity", "planned_unit", "created_by", "prov_description", "prov_action_type", "prov_responsible", "prov_due_date", "prov_priority", "prov_note", "prov_notify_school") VALUES (10, 'INF-2026-00010', 'Hidráulica — fgsgfdggg', 'vcxfgcx', 'Hidráulica', NULL, 'fgsgfdggg', NULL, 30, 0, 1, 2, 'P1', 'Recebida', '2026-08-29 01:06:01', '2026-08-29 11:40:58', NULL, NULL, NULL, 0.0, NULL, NULL, NULL, 0, 0, 0, 0, NULL, NULL, 0.0, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, 0) ON CONFLICT DO NOTHING;
INSERT INTO public.demands ("id", "code", "title", "description", "category", "subcategory", "location", "impact", "affected_people", "risk", "blocks_activity", "school_id", "priority", "status", "created_at", "updated_at", "due_date", "responsible", "sector", "cost_estimate", "action_defined", "technical_opinion", "dependencies", "needs_visit", "needs_budget", "needs_material", "needs_contract", "future_year", "planning_kind", "planned_quantity", "planned_unit", "created_by", "prov_description", "prov_action_type", "prov_responsible", "prov_due_date", "prov_priority", "prov_note", "prov_notify_school") VALUES (11, 'INF-2026-00011', 'Elétrica — ghj', 'ghj', 'Elétrica', NULL, 'ghj', NULL, 30, 0, 0, 2, 'P3', 'Nova', '2026-08-29 01:13:22', '2026-08-29 01:13:22', NULL, NULL, NULL, 0.0, NULL, NULL, NULL, 0, 0, 0, 0, NULL, NULL, 0.0, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, 0) ON CONFLICT DO NOTHING;

-- Inserindo 34 registro(s) em demand_updates
INSERT INTO public.demand_updates ("id", "demand_id", "kind", "message", "author", "visibility", "created_at") VALUES (1, 1, 'Criação', 'Demanda registrada no sistema.', 'Sistema', 'public', '2026-08-12 00:48:11') ON CONFLICT DO NOTHING;
INSERT INTO public.demand_updates ("id", "demand_id", "kind", "message", "author", "visibility", "created_at") VALUES (2, 1, 'Status', 'Status atualizado para Em execução.', 'Equipe de Infraestrutura', 'public', '2026-08-13 00:48:11') ON CONFLICT DO NOTHING;
INSERT INTO public.demand_updates ("id", "demand_id", "kind", "message", "author", "visibility", "created_at") VALUES (3, 2, 'Criação', 'Demanda registrada no sistema.', 'Sistema', 'public', '2026-08-13 00:48:11') ON CONFLICT DO NOTHING;
INSERT INTO public.demand_updates ("id", "demand_id", "kind", "message", "author", "visibility", "created_at") VALUES (4, 2, 'Status', 'Status atualizado para Aguardando contratação.', 'Equipe de Infraestrutura', 'public', '2026-08-14 00:48:11') ON CONFLICT DO NOTHING;
INSERT INTO public.demand_updates ("id", "demand_id", "kind", "message", "author", "visibility", "created_at") VALUES (5, 3, 'Criação', 'Demanda registrada no sistema.', 'Sistema', 'public', '2026-08-14 00:48:11') ON CONFLICT DO NOTHING;
INSERT INTO public.demand_updates ("id", "demand_id", "kind", "message", "author", "visibility", "created_at") VALUES (6, 3, 'Status', 'Status atualizado para Serviço programado.', 'Equipe de Infraestrutura', 'public', '2026-08-15 00:48:11') ON CONFLICT DO NOTHING;
INSERT INTO public.demand_updates ("id", "demand_id", "kind", "message", "author", "visibility", "created_at") VALUES (7, 4, 'Criação', 'Demanda registrada no sistema.', 'Sistema', 'public', '2026-08-15 00:48:11') ON CONFLICT DO NOTHING;
INSERT INTO public.demand_updates ("id", "demand_id", "kind", "message", "author", "visibility", "created_at") VALUES (8, 4, 'Status', 'Status atualizado para Planejamento futuro.', 'Equipe de Infraestrutura', 'public', '2026-08-16 00:48:11') ON CONFLICT DO NOTHING;
INSERT INTO public.demand_updates ("id", "demand_id", "kind", "message", "author", "visibility", "created_at") VALUES (9, 5, 'Criação', 'Demanda registrada no sistema.', 'Sistema', 'public', '2026-08-16 00:48:11') ON CONFLICT DO NOTHING;
INSERT INTO public.demand_updates ("id", "demand_id", "kind", "message", "author", "visibility", "created_at") VALUES (10, 5, 'Status', 'Status atualizado para Em análise técnica.', 'Equipe de Infraestrutura', 'public', '2026-08-17 00:48:11') ON CONFLICT DO NOTHING;
INSERT INTO public.demand_updates ("id", "demand_id", "kind", "message", "author", "visibility", "created_at") VALUES (11, 6, 'Criação', 'Demanda registrada no sistema.', 'Sistema', 'public', '2026-08-17 00:48:11') ON CONFLICT DO NOTHING;
INSERT INTO public.demand_updates ("id", "demand_id", "kind", "message", "author", "visibility", "created_at") VALUES (12, 6, 'Status', 'Status atualizado para Planejamento futuro.', 'Equipe de Infraestrutura', 'public', '2026-08-18 00:48:11') ON CONFLICT DO NOTHING;
INSERT INTO public.demand_updates ("id", "demand_id", "kind", "message", "author", "visibility", "created_at") VALUES (13, 7, 'Criação', 'Demanda registrada no sistema.', 'Sistema', 'public', '2026-08-18 00:48:11') ON CONFLICT DO NOTHING;
INSERT INTO public.demand_updates ("id", "demand_id", "kind", "message", "author", "visibility", "created_at") VALUES (14, 7, 'Status', 'Status atualizado para Concluída.', 'Equipe de Infraestrutura', 'public', '2026-08-19 00:48:11') ON CONFLICT DO NOTHING;
INSERT INTO public.demand_updates ("id", "demand_id", "kind", "message", "author", "visibility", "created_at") VALUES (15, 8, 'Criação', 'Demanda registrada no sistema.', 'Sistema', 'public', '2026-08-19 00:48:11') ON CONFLICT DO NOTHING;
INSERT INTO public.demand_updates ("id", "demand_id", "kind", "message", "author", "visibility", "created_at") VALUES (16, 8, 'Status', 'Status atualizado para Reprogramada.', 'Equipe de Infraestrutura', 'public', '2026-08-20 00:48:11') ON CONFLICT DO NOTHING;
INSERT INTO public.demand_updates ("id", "demand_id", "kind", "message", "author", "visibility", "created_at") VALUES (17, 9, 'Criação', 'Demanda registrada no sistema.', 'Gestor da Infraestrutura', 'public', '2026-08-29 01:01:38') ON CONFLICT DO NOTHING;
INSERT INTO public.demand_updates ("id", "demand_id", "kind", "message", "author", "visibility", "created_at") VALUES (18, 10, 'Criação', 'Demanda registrada no sistema.', 'Gestor da Infraestrutura', 'public', '2026-08-29 01:06:01') ON CONFLICT DO NOTHING;
INSERT INTO public.demand_updates ("id", "demand_id", "kind", "message", "author", "visibility", "created_at") VALUES (19, 10, 'Anexo', 'Arquivo anexado: energia explicação.png', 'Gestor da Infraestrutura', 'public', '2026-08-29 01:06:01') ON CONFLICT DO NOTHING;
INSERT INTO public.demand_updates ("id", "demand_id", "kind", "message", "author", "visibility", "created_at") VALUES (20, 10, 'Devolutiva', 'aguardando', 'Gestor da Infraestrutura', 'public', '2026-08-29 01:06:46') ON CONFLICT DO NOTHING;
INSERT INTO public.demand_updates ("id", "demand_id", "kind", "message", "author", "visibility", "created_at") VALUES (21, 11, 'Criação', 'Demanda registrada no sistema.', 'Gestor da Infraestrutura', 'public', '2026-08-29 01:13:22') ON CONFLICT DO NOTHING;
INSERT INTO public.demand_updates ("id", "demand_id", "kind", "message", "author", "visibility", "created_at") VALUES (22, 10, 'Alteração', 'Status: Nova → Em análise técnica', 'Gestor da Infraestrutura', 'public', '2026-08-29 01:56:20') ON CONFLICT DO NOTHING;
INSERT INTO public.demand_updates ("id", "demand_id", "kind", "message", "author", "visibility", "created_at") VALUES (23, 10, 'Alteração', 'Status: Em análise técnica → Recebida', 'Gestor da Infraestrutura', 'public', '2026-08-29 01:56:22') ON CONFLICT DO NOTHING;
INSERT INTO public.demand_updates ("id", "demand_id", "kind", "message", "author", "visibility", "created_at") VALUES (24, 8, 'Alteração', 'Status: Reprogramada → Em análise técnica', 'Gestor da Infraestrutura', 'public', '2026-08-29 02:29:41') ON CONFLICT DO NOTHING;
INSERT INTO public.demand_updates ("id", "demand_id", "kind", "message", "author", "visibility", "created_at") VALUES (25, 5, 'Alteração', 'Status: Em análise técnica → Aguardando contratação', 'Gestor da Infraestrutura', 'public', '2026-08-29 02:38:12') ON CONFLICT DO NOTHING;
INSERT INTO public.demand_updates ("id", "demand_id", "kind", "message", "author", "visibility", "created_at") VALUES (26, 1, 'Alteração', 'cost_estimate: 15400.0 → —; Exercício futuro: — → —', 'Gestor da Infraestrutura', 'public', '2026-08-29 02:50:16') ON CONFLICT DO NOTHING;
INSERT INTO public.demand_updates ("id", "demand_id", "kind", "message", "author", "visibility", "created_at") VALUES (27, 8, 'Alteração', 'Status: Em análise técnica → Recebida', 'Gestor da Infraestrutura', 'public', '2026-08-29 09:37:18') ON CONFLICT DO NOTHING;
INSERT INTO public.demand_updates ("id", "demand_id", "kind", "message", "author", "visibility", "created_at") VALUES (28, 8, 'Alteração', 'Status: Recebida → Em análise técnica', 'Gestor da Infraestrutura', 'public', '2026-08-29 09:37:20') ON CONFLICT DO NOTHING;
INSERT INTO public.demand_updates ("id", "demand_id", "kind", "message", "author", "visibility", "created_at") VALUES (29, 2, 'Alteração', 'Status: Aguardando contratação → Em análise técnica', 'Gestor da Infraestrutura', 'public', '2026-08-29 09:37:24') ON CONFLICT DO NOTHING;
INSERT INTO public.demand_updates ("id", "demand_id", "kind", "message", "author", "visibility", "created_at") VALUES (30, 10, 'Alteração', 'Status: Recebida → Em análise técnica', 'Gestor da Infraestrutura', 'public', '2026-08-29 11:40:57') ON CONFLICT DO NOTHING;
INSERT INTO public.demand_updates ("id", "demand_id", "kind", "message", "author", "visibility", "created_at") VALUES (31, 10, 'Alteração', 'Status: Em análise técnica → Recebida', 'Gestor da Infraestrutura', 'public', '2026-08-29 11:40:58') ON CONFLICT DO NOTHING;
INSERT INTO public.demand_updates ("id", "demand_id", "kind", "message", "author", "visibility", "created_at") VALUES (32, 5, 'Alteração', 'Exercício futuro: — → 2027; planning_kind: — → Obra futura; planned_quantity: — → 1.0; planned_unit: — → serviço', 'Gestor da Infraestrutura', 'public', '2026-08-30 18:36:14') ON CONFLICT DO NOTHING;
INSERT INTO public.demand_updates ("id", "demand_id", "kind", "message", "author", "visibility", "created_at") VALUES (33, 6, 'Alteração', 'cost_estimate: 145000.0 → 144000.0', 'Gestor da Infraestrutura', 'public', '2026-08-30 18:37:10') ON CONFLICT DO NOTHING;
INSERT INTO public.demand_updates ("id", "demand_id", "kind", "message", "author", "visibility", "created_at") VALUES (34, 5, 'Alteração', 'Exercício futuro: 2027 → —; planning_kind: Obra futura → —; planned_quantity: 1.0 → —; planned_unit: serviço → —', 'Gestor da Infraestrutura', 'public', '2026-08-30 18:37:19') ON CONFLICT DO NOTHING;

-- Inserindo 1 registro(s) em attachments
INSERT INTO public.attachments ("id", "demand_id", "filename", "stored_name", "mime", "size", "created_at") VALUES (1, 10, 'energia explicação.png', '10_a07cc4b8f2a3018799e0.png', 'image/png', 1452645, '2026-08-29 01:06:01') ON CONFLICT DO NOTHING;

-- Inserindo 4 registro(s) em planning_items
INSERT INTO public.planning_items ("id", "code", "year", "title", "category", "kind", "status", "estimated_cost", "quantity", "unit", "justification", "schools_count", "process_number", "procurement_number", "contract_number", "supplier", "created_at", "updated_at") VALUES (1, 'PLAN-2027-0001', 2027, 'Aquisição de aparelhos de ar-condicionado Split 12k BTU', 'Climatização', 'Aquisição futura', 'Aprovada para planejamento', 145000.0, 41.0, 'un', 'Consolidar necessidades de climatização de 12 unidades.', 12, NULL, NULL, NULL, NULL, '2026-08-29 00:48:11', '2026-08-29 00:48:11') ON CONFLICT DO NOTHING;
INSERT INTO public.planning_items ("id", "code", "year", "title", "category", "kind", "status", "estimated_cost", "quantity", "unit", "justification", "schools_count", "process_number", "procurement_number", "contract_number", "supplier", "created_at", "updated_at") VALUES (2, 'PLAN-2027-0002', 2027, 'Atualização de infraestrutura de rede (Cat6a)', 'Equipamentos', 'Contratação futura', 'Em levantamento', 85500.0, 8.0, 'unidades', 'Modernização de rede lógica e cabeamento estruturado.', 8, NULL, NULL, NULL, NULL, '2026-08-29 00:48:11', '2026-08-29 00:48:11') ON CONFLICT DO NOTHING;
INSERT INTO public.planning_items ("id", "code", "year", "title", "category", "kind", "status", "estimated_cost", "quantity", "unit", "justification", "schools_count", "process_number", "procurement_number", "contract_number", "supplier", "created_at", "updated_at") VALUES (3, 'PLAN-2027-0003', 2027, 'Reposição de equipamentos de laboratório', 'Equipamentos', 'Aquisição futura', 'Aguardando estimativa', 32000.0, 18.0, 'itens', 'Reposição de equipamentos danificados e obsoletos.', 5, NULL, NULL, NULL, NULL, '2026-08-29 00:48:11', '2026-08-29 00:48:11') ON CONFLICT DO NOTHING;
INSERT INTO public.planning_items ("id", "code", "year", "title", "category", "kind", "status", "estimated_cost", "quantity", "unit", "justification", "schools_count", "process_number", "procurement_number", "contract_number", "supplier", "created_at", "updated_at") VALUES (4, 'PLAN-2028-0004', 2028, 'Projeto de instalação de painéis solares — Fase 1', 'Obra', 'Projeto futuro', 'Rascunho', 450000.0, 3.0, 'unidades', 'Projeto-piloto de eficiência energética.', 3, NULL, NULL, NULL, NULL, '2026-08-29 00:48:11', '2026-08-29 00:48:11') ON CONFLICT DO NOTHING;

-- 5. AJUSTE DE SEQUÊNCIAS DE ID (AUTO INCREMENTO)
---------------------------------------------------------------------------
SELECT setval(pg_get_serial_sequence('public.schools', 'id'), COALESCE(max(id), 1)) FROM public.schools;
SELECT setval(pg_get_serial_sequence('public.users', 'id'), COALESCE(max(id), 1)) FROM public.users;
SELECT setval(pg_get_serial_sequence('public.access_profiles', 'id'), COALESCE(max(id), 1)) FROM public.access_profiles;
SELECT setval(pg_get_serial_sequence('public.categories', 'id'), COALESCE(max(id), 1)) FROM public.categories;
SELECT setval(pg_get_serial_sequence('public.priority_levels', 'id'), COALESCE(max(id), 1)) FROM public.priority_levels;
SELECT setval(pg_get_serial_sequence('public.kanban_stages', 'id'), COALESCE(max(id), 1)) FROM public.kanban_stages;
SELECT setval(pg_get_serial_sequence('public.demands', 'id'), COALESCE(max(id), 1)) FROM public.demands;
SELECT setval(pg_get_serial_sequence('public.demand_updates', 'id'), COALESCE(max(id), 1)) FROM public.demand_updates;
SELECT setval(pg_get_serial_sequence('public.attachments', 'id'), COALESCE(max(id), 1)) FROM public.attachments;
SELECT setval(pg_get_serial_sequence('public.planning_items', 'id'), COALESCE(max(id), 1)) FROM public.planning_items;